/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework.gui;

import com.sun.org.apache.bcel.internal.generic.INSTANCEOF;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanyuu
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Ссылка на самого себя, для реализации паттерна синглтон.
     * http://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BD%D0%B3%D0%BB%D1%82%D0%BE%D0%BD
     */
    private static GUI __instance=null;
    
    public static GUI getInstance(){
        if(__instance==null)
            return new GUI();
        else
            return __instance;
    }
    /**
     * Creates new form GUI
     */
    private GUI() {
        if (__instance==null)
            initComponents();            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        liters_per_kilometer = new javax.swing.JTextField();
        kilemetors = new javax.swing.JTextField();
        calc = new javax.swing.JButton();
        result = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        calc.setText("Посчитать");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });

        result.setEditable(false);

        jLabel1.setText("Литров на километр");

        jLabel2.setText("Километраж");

        jLabel3.setText("Результат");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(kilemetors, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(liters_per_kilometer, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liters_per_kilometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kilemetors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(calc)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        double lpk=-1,kilometers=-1;
        try{
            lpk=Double.parseDouble(this.liters_per_kilometer.getText());
        }catch(NumberFormatException nfe){
            this.showMessage("В поле \"Литры на километр\" введены не верные данные.\nДопускаются только цифры и точка.", 0);
        }
        try{
            kilometers=Double.parseDouble(this.kilemetors.getText());
        }catch(NumberFormatException nfe){
            this.showMessage("В поле \"Километраж\" введены не верные данные.\nДопускаются только цифры и точка.", 0);
        }
        if(lpk!=-1&&kilometers!=-1){
            this.result.setText(String.valueOf(lpk*kilometers));
        }
    }//GEN-LAST:event_calcActionPerformed

    private void showMessage(String msg, int type){
        JOptionPane.showMessageDialog(this, msg, "", type);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField kilemetors;
    private javax.swing.JTextField liters_per_kilometer;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
